const BUILDINGS = {
    39: { "id": 39, "slug": "command_tower", "recipes": [], "encombrement_bonus": 50, "isUnique": true, "energy": 50, "storage_su": 500 },
    40: { "id": 40, "slug": "extractor", "recipes": [], "encombrement": 5, "energy": 20 },
    41: { "id": 41, "slug": "solar_plant", "recipes": [], "encombrement": 10, "energy": 10 },
    42: { "id": 42, "slug": "pylon", "recipes": [] },
    43: { 
        "id": 43, 
        "slug": "foundry", 
        "encombrement": 3,
        "energy": -4,
        "recipes": [
            { "ingredients": { "62": 3, "Kaolinite": 1 }, "outputs": { "Lingot d'alu-K": 3 }, "duration": "22.5s / 4m 30s" },
            { "ingredients": { "Minerai d'aluminium": 2 }, "outputs": { "62": 1 }, "duration": "5s / 3m" },
            { "ingredients": { "Émeraude": 3, "62": 1 }, "outputs": { "3": 2 }, "duration": "15s / 9m" },
            { "ingredients": { "Pépite d'aluminium": 4 }, "outputs": { "62": 1 }, "duration": "5s / 3m" },
            { "ingredients": { "67": 4, "26": 1 }, "outputs": { "Lingot de titane-B": 3 }, "duration": "22.5s / 4m 30s" },
            { "ingredients": { "Poudre de quartz": 3, "65": 1 }, "outputs": { "15": 7 }, "duration": "5s / 3m" },
            { "ingredients": { "65": 2 }, "outputs": { "15": 5 }, "duration": "10s / 6m" },
            { "ingredients": { "Minerai de cuivre": 2 }, "outputs": { "2": 1 }, "duration": "5s / 3m" },
            { "ingredients": { "Azurite": 1 }, "outputs": { "2": 4 }, "duration": "5s / 3m" },
            { "ingredients": { "Malachite": 1 }, "outputs": { "2": 4 }, "duration": "5s / 3m" },
            { "ingredients": { "Pépite de cuivre": 4 }, "outputs": { "2": 1 }, "duration": "5s / 3m" },
            { "ingredients": { "Pépite d'elmérium": 3 }, "outputs": { "66": 1 }, "duration": "5s / 3m" },
            { "ingredients": { "Poussière d'elmérium": 50 }, "outputs": { "66": 1 }, "duration": "5s / 3m" },
            { "ingredients": { "Minerai de fer": 2 }, "outputs": { "1": 1 }, "duration": "5s / 3m" },
            { "ingredients": { "Hématite": 1 }, "outputs": { "1": 1 }, "duration": "5s / 3m" },
            { "ingredients": { "Pépite de fer": 4 }, "outputs": { "1": 1 }, "duration": "5s / 3m" },
            { "ingredients": { "17": 1 }, "outputs": { "Chaux": 5 }, "duration": "5s / 3m" },
            { "ingredients": { "Minerai de platine": 2 }, "outputs": { "Lingot de platine": 1 }, "duration": "5s / 3m" },
            { "ingredients": { "Pépite de platine": 4 }, "outputs": { "Lingot de platine": 1 }, "duration": "5s / 3m" },
            { "ingredients": { "Aigue-marine": 3, "3": 2, "62": 1 }, "outputs": { "3": 2 }, "duration": "15s / 9m" },
            { "ingredients": { "31": 1 }, "outputs": { "3": 1 }, "duration": "10s / 6m" },
            { "ingredients": { "65": 12 }, "outputs": { "3": 1 }, "duration": "20s / 12m" },
            { "ingredients": { "Poudre de quartz": 20 }, "outputs": { "3": 1 }, "duration": "20s / 12m" },
            { "ingredients": { "Pépite d'argent": 4 }, "outputs": { "Lingot d'argent": 1 }, "duration": "5s / 3m" },
            { "ingredients": { "1": 4, "64": 4 }, "outputs": { "63": 3 }, "duration": "25s / 6m" },
            { "ingredients": { "33": 1, "Soufre": 4 }, "outputs": { "1": 1 }, "duration": "8s / 4m 48s" },
            { "ingredients": { "Minerai de titane": 2 }, "outputs": { "67": 1 }, "duration": "5s / 3m" },
            { "ingredients": { "Pépite de titane": 4 }, "outputs": { "67": 1 }, "duration": "5s / 3m" },
            { "ingredients": { "Minerai de tungstène": 2 }, "outputs": { "Lingot de tungstène": 1 }, "duration": "5s / 3m" },
            { "ingredients": { "Pépite de tungstène": 4 }, "outputs": { "Lingot de tungstène": 1 }, "duration": "5s / 3m" },
            { "ingredients": { "Lingot de platine": 4, "Lingot de tungstène": 4, "3": 1 }, "outputs": { "Lingot de rigidium": 6 }, "duration": "30s / 6m" },
            { "ingredients": { "Minerai de vanadium": 2 }, "outputs": { "26": 1 }, "duration": "5s / 3m" },
            { "ingredients": { "Minerai de zirconium": 2 }, "outputs": { "Lingot de zirconium": 1 }, "duration": "5s / 3m" },
            { "ingredients": { "Pépite de zirconium": 4 }, "outputs": { "Lingot de zirconium": 1 }, "duration": "5s / 3m" }
        ]
    },
    44: { "id": 44, "slug": "micro_furnace", "recipes": [], "encombrement": 1 },
    45: { "id": 45, "slug": "assembler", "recipes": [], "encombrement": 3, "energy": -4 },
    46: { "id": 46, "slug": "chemical_plant", "recipes": [], "encombrement": 3 },
    47: { "id": 47, "slug": "crystallizer", "recipes": [], "encombrement": 5 },
    48: { "id": 48, "slug": "warehouse", "recipes": [], "encombrement": 3, "storage_su": 2000 },
    49: { "id": 49, "slug": "exchange_box", "recipes": [], "encombrement": 1, "storage_su": 400 },
    50: { "id": 50, "slug": "drone_hub", "recipes": [], "encombrement": 1 },
    51: { "id": 51, "slug": "tank", "recipes": [], "encombrement": 3, "storage_liquid": 4000 },
    52: { "id": 52, "slug": "mag_plasma_tank", "recipes": [], "encombrement": 5, "storage_liquid": 2000, "liquid_restriction": "mag-plasma" },
    53: { "id": 53, "slug": "landing_pad", "recipes": [], "encombrement": 1 },
    54: { "id": 54, "slug": "space_shipyard", "recipes": [], "encombrement": 3 },
    55: { "id": 55, "slug": "xenic_farm", "recipes": [], "encombrement": 5 },
    56: { "id": 56, "slug": "fuel_plant", "recipes": [], "encombrement": 3, "energy": 40 },
    57: { "id": 57, "slug": "battery_cluster", "recipes": [], "encombrement": 1 },
    58: { "id": 58, "slug": "liquid_extractor", "recipes": [], "encombrement": 5 },
    59: { "id": 59, "slug": "packaging_plant", "recipes": [] },
    60: { "id": 60, "slug": "factory", "recipes": [], "encombrement": 10, "energy": -10 },
    71: { "id": 71, "slug": "simple_command_center", "recipes": [], "encombrement_bonus": 50, "isUnique": true, "energy": 50, "storage_su": 500 }
};

const NODE_DICTIONARY = {
    101: "Gisement de fer dense",
    102: "Gisement de cuivre dense",
    103: "Gisement de fer",
    104: "Gisement de charbon",
    105: "Gisement de grès",
    106: "Gisement de cuivre",
    107: "Gisement de titane",
    108: "Gisement d'aluminium",
    109: "Gisement de platine",
    110: "Bassin de saumure",
    111: "Bassin de vitriol"
};

const NODES = {
    101: { "id": 101, "slug": "dense_iron_node", "performance": { "resource": "Pépite de fer", "rate": 120 } },
    102: { "id": 102, "slug": "dense_copper_node", "performance": { "resource": "Pépite de cuivre", "rate": 120 } },
    103: { "id": 103, "slug": "iron_node", "performance": { "resource": "Minerai de fer", "rate": 60 } },
    104: { "id": 104, "slug": "coal_node", "performance": { "resource": "Carbone-a", "rate": 40 } },
    105: { "id": 105, "slug": "sandstone_node", "performance": { "resource": "Silicate", "rate": 100 } },
    106: { "id": 106, "slug": "copper_node", "performance": { "resource": "Minerai de cuivre", "rate": 60 } },
    107: { "id": 107, "slug": "titanium_node", "performance": { "resource": "Minerai de titane", "rate": 60 } },
    108: { "id": 108, "slug": "aluminum_node", "performance": { "resource": "Minerai d'aluminium", "rate": 60 } },
    109: { "id": 109, "slug": "platinum_node", "performance": { "resource": "Minerai de platine", "rate": 60 } },
    110: { "id": 110, "slug": "brine_pool", "performance": { "resource": "Eau", "rate": 400 } },
    111: { "id": 111, "slug": "vitriol_pool", "performance": { "resource": "Acide", "rate": 400 } }
};