const BUILDINGS = {
    39: { "id": 39, "slug": "command_tower", "recipes": [], "encombrement_bonus": 50, "isUnique": true, "energy": 50, "storage_su": 500 },
    40: { "id": 40, "slug": "extractor", "recipes": [], "encombrement": 5, "energy": 20 },
    41: { "id": 41, "slug": "solar_plant", "recipes": [], "encombrement": 10, "energy": 10 },
    42: { "id": 42, "slug": "pylon", "recipes": [] },
    43: { 
        "id": 43, 
        "slug": "foundry", 
        "encombrement": 3,
        "energy": -4,
        "recipes": [
            { "ingredients": { "62": 3, "150": 1 }, "outputs": { "151": 3 }, "items_per_hour": 40, "energy": -12 },
            { "ingredients": { "152": 2 }, "outputs": { "62": 1 }, "items_per_hour": 20, "energy": -8 },
            { "ingredients": { "153": 3, "62": 1 }, "outputs": { "3": 2 }, "items_per_hour": 13.33, "energy": -4 },
            { "ingredients": { "154": 4 }, "outputs": { "62": 1 }, "items_per_hour": 20, "energy": -5 },
            { "ingredients": { "67": 4, "26": 1 }, "outputs": { "155": 3 }, "items_per_hour": 40, "energy": -12 },
            { "ingredients": { "156": 3, "65": 1 }, "outputs": { "15": 7 }, "items_per_hour": 140 },
            { "ingredients": { "65": 2 }, "outputs": { "15": 5 }, "items_per_hour": 50, "energy": -5 },
            { "ingredients": { "157": 2 }, "outputs": { "2": 1 }, "items_per_hour": 20, "energy": -8 },
            { "ingredients": { "158": 1 }, "outputs": { "2": 4 }, "items_per_hour": 80, "energy": -4 },
            { "ingredients": { "159": 1 }, "outputs": { "2": 4 }, "items_per_hour": 80, "energy": -4 },
            { "ingredients": { "160": 4 }, "outputs": { "2": 1 }, "items_per_hour": 20, "energy": -5 },
            { "ingredients": { "161": 3 }, "outputs": { "66": 1 }, "items_per_hour": 20, "energy": -5 },
            { "ingredients": { "162": 50 }, "outputs": { "66": 1 }, "items_per_hour": 20, "energy": -8 },
            { "ingredients": { "163": 2 }, "outputs": { "1": 1 }, "items_per_hour": 20, "energy": -8 },
            { "ingredients": { "164": 1 }, "outputs": { "1": 1 }, "items_per_hour": 20, "energy": -4 },
            { "ingredients": { "165": 4 }, "outputs": { "1": 1 }, "items_per_hour": 20, "energy": -5 },
            { "ingredients": { "17": 1 }, "outputs": { "166": 5 }, "items_per_hour": 100, "energy": -4 },
            { "ingredients": { "167": 2 }, "outputs": { "168": 1 }, "items_per_hour": 20, "energy": -8 },
            { "ingredients": { "169": 4 }, "outputs": { "168": 1 }, "items_per_hour": 20, "energy": -5 },
            { "ingredients": { "170": 3, "3": 2, "62": 1 }, "outputs": { "3": 2 }, "items_per_hour": 13.33, "energy": -4 },
            { "ingredients": { "31": 1 }, "outputs": { "3": 1 }, "items_per_hour": 10, "energy": -4 },
            { "ingredients": { "65": 12 }, "outputs": { "3": 1 }, "items_per_hour": 5, "energy": -8 },
            { "ingredients": { "156": 20 }, "outputs": { "3": 1 }, "items_per_hour": 5, "energy": -4 },
            { "ingredients": { "171": 4 }, "outputs": { "172": 1 }, "items_per_hour": 20, "energy": -5 },
            { "ingredients": { "1": 4, "64": 4 }, "outputs": { "63": 3 }, "items_per_hour": 30, "energy": -12 },
            { "ingredients": { "33": 1, "173": 4 }, "outputs": { "1": 1 }, "items_per_hour": 12.5 },
            { "ingredients": { "174": 2 }, "outputs": { "67": 1 }, "items_per_hour": 20, "energy": -8 },
            { "ingredients": { "175": 4 }, "outputs": { "67": 1 }, "items_per_hour": 20, "energy": -5 },
            { "ingredients": { "176": 2 }, "outputs": { "177": 1 }, "items_per_hour": 20, "energy": -8 },
            { "ingredients": { "178": 4 }, "outputs": { "177": 1 }, "items_per_hour": 20, "energy": -5 },
            { "ingredients": { "168": 4, "177": 4, "3": 1 }, "outputs": { "179": 6 }, "items_per_hour": 60, "energy": -12 },
            { "ingredients": { "180": 2 }, "outputs": { "26": 1 }, "items_per_hour": 20, "energy": -8 },
            { "ingredients": { "181": 2 }, "outputs": { "182": 1 }, "items_per_hour": 20, "energy": -8 },
            { "ingredients": { "183": 4 }, "outputs": { "182": 1 }, "items_per_hour": 20, "energy": -5 }
        ]
    },
    44: { "id": 44, "slug": "micro_furnace", "recipes": [], "encombrement": 1 },
    45: { "id": 45, "slug": "assembler", "recipes": [], "encombrement": 3, "energy": -4 },
    46: { "id": 46, "slug": "chemical_plant", "recipes": [], "encombrement": 3 },
    47: { "id": 47, "slug": "crystallizer", "recipes": [], "encombrement": 5 },
    48: { "id": 48, "slug": "warehouse", "recipes": [], "encombrement": 3, "storage_su": 2000 },
    49: { "id": 49, "slug": "exchange_box", "recipes": [], "encombrement": 1, "storage_su": 400 },
    50: { "id": 50, "slug": "drone_hub", "recipes": [], "encombrement": 1 },
    51: { "id": 51, "slug": "tank", "recipes": [], "encombrement": 3, "storage_liquid": 4000 },
    52: { "id": 52, "slug": "mag_plasma_tank", "recipes": [], "encombrement": 5, "storage_liquid": 2000, "liquid_restriction": "mag-plasma" },
    53: { "id": 53, "slug": "landing_pad", "recipes": [], "encombrement": 1 },
    54: { "id": 54, "slug": "space_shipyard", "recipes": [], "encombrement": 3 },
    55: { "id": 55, "slug": "xenic_farm", "recipes": [], "encombrement": 5 },
    56: { "id": 56, "slug": "fuel_plant", "recipes": [], "encombrement": 3, "energy": 40 },
    57: { "id": 57, "slug": "battery_cluster", "recipes": [], "encombrement": 1 },
    58: { "id": 58, "slug": "liquid_extractor", "recipes": [], "encombrement": 5 },
    59: { "id": 59, "slug": "packaging_plant", "recipes": [] },
    60: { "id": 60, "slug": "factory", "recipes": [], "encombrement": 10, "energy": -10 },
    71: { "id": 71, "slug": "simple_command_center", "recipes": [], "encombrement_bonus": 50, "isUnique": true, "energy": 50, "storage_su": 500 }
};